Visual(Interfaze)/SuperNaaahi/SuperNaaahi/Controllers/ReportController.cs
using AspNetCore.Reporting;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using SuperNaaahi.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SuperNaaahi.Controllers
    {
    /// <summary>
    /// Reportea egiteko kontrolerra
    /// </summary>
    public class ReportController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IPuntuazioaService _puntuazioaService;

        /// <summary>
        /// ReportControlerraren konstruktorea
        /// </summary>
        /// <param name="webHostEnvironment"></param>
        /// <param name="puntuazioaService"></param>
        public ReportController(IWebHostEnvironment webHostEnvironment, IPuntuazioaService puntuazioaService)
        {
            _webHostEnvironment = webHostEnvironment;
            _puntuazioaService = puntuazioaService;
        }

        /// <summary>
        /// Informea inprimtatu
        /// </summary>
        /// <returns>informea pdf</returns>
        public async Task<IActionResult> InprimatuHallOf()
        {
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

            string mimtype = "";
            int extension = 1;
            var path = $"{_webHostEnvironment.WebRootPath}\\Reports\\SuperNaaahiReport.rdlc";
            Dictionary<string, string> parameters = new Dictionary<string, string>();
           

            var hallOfFame = await _puntuazioaService.GetHallOfFame();
            var hallOfShame = await _puntuazioaService.GetHallOfShame();

            LocalReport localReport=new LocalReport(path);
            localReport.AddDataSource("DataSetHallOfFame", hallOfFame);
            localReport.AddDataSource("DataSetHallOfShame", hallOfShame);
            var result = localReport.Execute(RenderType.Pdf, extension, parameters, mimtype);
            return File(result.MainStream, "application/pdf");

        }
        public async Task<IActionResult> InprimatuRankingOrokorra()
        {
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

            string mimtype = "";
            int extension = 1;
            var path = $"{_webHostEnvironment.WebRootPath}\\Reports\\SuperNaaahiRankingOrokorReport.rdlc";
            Dictionary<string, string> parameters = new Dictionary<string, string>();
           


            var rankingOrokor = await _puntuazioaService.GetPuntuazioak();

            var kopurua = await _puntuazioaService.GetPartidaKopurua();
            parameters.Add("partidaKopurua", kopurua.ToString());

            LocalReport localReport = new LocalReport(path);
            
            localReport.AddDataSource("DataSetRanking", rankingOrokor);
            var result = localReport.Execute(RenderType.Pdf, extension, parameters, mimtype);
            return File(result.MainStream, "application/pdf");

        }

    }
}

Visual(Interfaze)/SuperNaaahi/SuperNaaahi/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SuperNaaahi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" href="/images/logo_size.jpg">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css" />


</head>
<body>

    <div class="container">


        <img src="~/images/logo_size.jpg" />
        <div class="logindiv">
            <partial name="_LoginPartial" />
        </div>
        <header>

            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom shadow mb-5">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SuperNaaahi</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="General">Ranking orokorra</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="HallOfFame">Hall of Fame</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="HallOfShame">Hall of Shame</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark " asp-area="" asp-controller="Home" asp-action="Foroa">Foroa</a>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Txostenak</a>
                                <div class="dropdown-content">
                                    <a class="dropdown-item" asp-controller="Report" asp-action="InprimatuHallOf">HallOfFame / HallOfShame</a>
                                    <a class="dropdown-item" asp-controller="Report" asp-action="InprimatuRankingOrokorra">Ranking Orokorra</a>
                                </div>
                            </li>

                        </ul>

                    </div>
                </div>
            </nav>


        </header>
    </div>
    <!--
        <li class="nav-item dropdown">
         <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             <b>Partidak</b>
         </a>
         <div class="dropdown-menu" aria-labelledby="navbarDropdown">
             <a class="nav-link dropdown" asp-area="" asp-controller="Home" asp-action="Partidak">Partidak</a>
             <a class="nav-link dropdown" asp-area="" asp-controller="Home" asp-action="HallOfFame">HallOfFame</a>
             <a class="nav-link dropdown" asp-area="" asp-controller="Home" asp-action="HallOfShame">HallOfShame</a>
         </div>
     </li>
    -->
    


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SuperNaaahi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#tabla').DataTable();
        });
    </script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>