Visual(Interfaze)/SuperNaaahi/SuperNaaahi/Models/Foroa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SuperNaaahi.Models
{
    /// <summary>
    /// Foroa egiteko modeloa
    /// </summary>
    public class Foroa
    {
        /// <summary>
        /// Id: priamry key eta  [ScaffoldColumn(false)] id eremua ez dugu hartuko
        /// </summary>
        [Key]
        [ScaffoldColumn(false)]
        public int Id{ get; set; }
        /// <summary>
        /// Korreoa derrigorrez sartu eta formatu egokiarekin
        /// </summary>
        [Required(ErrorMessage = "Zure korreoa derrigorrez sartu behar duzu.")] 
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Korreoaren formatua gaizki dago.")]
        public string Korreoa { get; set; }
        /// <summary>
        /// Komentarioa derrigorrez sartu
        /// </summary>
        [Required(ErrorMessage = "Derrigorrez zerbait komentatu behar duzu.")]
        public string Komentarioa { get; set; }
        /// <summary>
        /// [ScaffoldColumn(false)] data eramua ez dugu hartuko
        /// </summary>
        [ScaffoldColumn(false)]
        public System.DateTime Data { get; set; }
    }
}

Visual(Interfaze)/SuperNaaahi/SuperNaaahi/Models/Inkesta.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SuperNaaahi.Models
{
    /// <summary>
    /// Inkesta egiteko modeloa
    /// </summary>
    public class Inkesta
    {
        /// <summary>
        /// Korreoa derrigorrezkoa, formato egokiarekin eta primary key
        /// </summary>
        [Key]
        [Required(ErrorMessage ="Zure korreoa derrigorrez sartu behar duzu.")] // Korreoa derrigorrezkoa izateko
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Korreoaren formatua gaizki dago.")] // Korreoaren formatua konprobatzeko
        public string Korreoa { get; set; }
        /// <summary>
        /// Balorazioa derrigorrez ebte 1-10
        /// </summary>
        [Required(ErrorMessage = "Balorazioa derrigorrez sartu behar duzu.")] // Balorazioa derrigorrezkoa izateko
        public int Balorazioa { get; set; }
        /// <summary>
        /// Hobetzeko komentarioa
        /// </summary>
        public string Hobetzeko { get; set; }
        /// <summary>
        /// Bai ala ez gomendatu
        /// </summary>
        public bool Gomendatu { get; set; }
    }
}

Visual(Interfaze)/SuperNaaahi/SuperNaaahi/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SuperNaaahi.Models;
using SuperNaaahi.Services;

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SuperNaaahi.Controllers
{
    ///<sumary>
    /// Home karpetan dauden bistak kontrolatzeko
    /// </sumary>
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IInkestaService _inkestaService;
        private readonly IForoaService _foroaService;
        private readonly IPuntuazioaService _puntuazioaService;

        /// <summary>
        /// HomeControllerraren konstruktorea
        /// </summary>
        /// <param name="logger"></param>
        /// <param name="inkestaService"></param>
        /// <param name="foroaService"></param>
        /// <param name="puntuazioaService"></param>
        public HomeController(ILogger<HomeController> logger, IInkestaService inkestaService, IForoaService foroaService, IPuntuazioaService puntuazioaService)
        {
            _logger = logger;
            _inkestaService = inkestaService;
            _foroaService = foroaService;
            _puntuazioaService = puntuazioaService;

        }

        /// <summary>
        /// Index bista (Pagina nagusia) bistaratzeko
        /// </summary>
        /// <returns> Index View-a itzuli</returns>

        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// General bista (Puntuazio guztiak) bistaratzeko
        /// </summary>
        /// <returns>General View-a (Ranking orokorra) itzuli </returns>
        public IActionResult General(string puntua)
        {
            return View();
        }
  
      
      
        /// <summary>
        /// HallOfFame bista (Puntuazio onenak) bistaratzeko
        /// </summary>
        /// <returns>Puntuazio onenaren View-a itzuli </returns>
        public IActionResult HallOfFame()
        {
            return View();
        }


        /// <summary>
        /// HallOfShame bista (Puntuazio txarrenak) bistaratzeko
        /// </summary>
        /// <returns>Puntuazio txarrenan View-a itzuli</returns>
        public IActionResult HallOfShame()
        {
            return View();
        }

        /// <summary>
        /// Foroa bista bistaratzeko
        /// Authorize: Foroa egiteko logeatuta egon behar duzu
        /// </summary>
        /// <returns>Foroaren View-a itzuli</returns>
        [Authorize]
        public IActionResult Foroa()
        {
            return View();
        }
        /// <summary>
        /// Foroa egin
        /// </summary>
        /// <param name="Foroa"></param>
        /// <returns>View-a itzuli</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Foroa(Foroa Foroa)
        {
            try
            {
                Foroa.Data = DateTime.Now;
                _foroaService.Komentatu(Foroa);
                return View();
            }
            catch
            {
                ViewBag.Alert = "Erabiltzaile honek inkesta beteta dauka";
                return View();
            }
        }

        /// <summary>
        /// Email bereko inkesta bistaratu inkesta orrian
        /// Authorize: Inkesta egiteko logeatuta egon behar duzu
        /// </summary>
        /// <returns>Inkestaren informazioa beteta badago</returns>
        [Authorize]
        public async Task<IActionResult> Inkesta()
        {
            Inkesta inkesta = await _inkestaService.KonprobatuKorreoa(HttpContext.User.Identity.Name);
            return View(inkesta);
        }

        /// <summary>
        /// Inkesta bete, iadanik inkesta beteta badago aukera daukazu aldaketak egiteko
        /// </summary>
        /// <param name="inkesta"></param>
        /// <returns>Inkesta egin eta Index View-a itzuli</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>Inkesta(Inkesta inkesta)
        {
            if (ModelState.IsValid)
            {
                if((await _inkestaService.KonprobatuKorreoa(inkesta.Korreoa) != null))
                {
                    await _inkestaService.InkestaAldatu(inkesta);
                }
                else
                {
                    await _inkestaService.InkestaBete(inkesta);
                }
            }
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        ///  Privacy bista bistaratzeko
        /// </summary>
        /// <returns>Privacy View-a itzuli</returns>
        public IActionResult Privacy()
        {
            return View();
        }

        /// <summary>
        /// Erroreak bistaratu
        /// </summary>
        /// <returns>Errorea View-a</returns>
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Visual(Interfaze)/SuperNaaahi/SuperNaaahi/ViewComponents/ForoaViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SuperNaaahi.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SuperNaaahi.ViewComponents
{
    /// <summary>
    /// Foroa view-rako konponenteen view-a kudeatzeko
    /// </summary>
    public class ForoaViewComponent:ViewComponent
    {
        private readonly IForoaService _foroaService;
        /// <summary>
        /// Foroa ViewConponent-earen konstruktorea
        /// </summary>
        /// <param name="foroaService"></param>
        public ForoaViewComponent(IForoaService foroaService)
        {
            _foroaService = foroaService;
        }
        /// <summary>
        /// Viee-ra bidaltzen dio komentarioen informazioa
        /// </summary>
        /// <returns> Komentarioaren lista itzuli</returns>
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await _foroaService.KomentarioakLortu());

        }
    }
}

Visual(Interfaze)/SuperNaaahi/SuperNaaahi/ViewComponents/HallOfFameViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SuperNaaahi.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SuperNaaahi.ViewComponents
{
    /// <summary>
    /// Putnuazio onenaren view-rako konponenteen view-a kudeatzeko 
    /// </summary>
    public class HallOfFameViewComponent: ViewComponent
    {
        private readonly IPuntuazioaService _puntuazioaService;
        /// <summary>
        /// Puntuazio onenaren ViewConponent-earen konstruktorea
        /// </summary>
        /// <param name="puntuazioaService"></param>
        public HallOfFameViewComponent(IPuntuazioaService puntuazioaService)
        {
            _puntuazioaService = puntuazioaService;
        }
        /// <summary>
        /// View-ra bidaltzen dio puntuazio onenen informazioa
        /// </summary>
        /// <returns></returns>
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await _puntuazioaService.GetHallOfFame());

        }
    }
}

Visual(Interfaze)/SuperNaaahi/SuperNaaahi/ViewComponents/HallOfShameViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SuperNaaahi.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SuperNaaahi.ViewComponents
{
    /// <summary>
    /// Puntuazio txarrenaren view-rako konponenteen viw-a
    /// </summary>
    public class HallOfShameViewComponent:ViewComponent
    {
        private readonly IPuntuazioaService _puntuazioaService;
        /// <summary>
        /// Puntuazio txarrenaren ViewComponet-aren Konstruktorea
        /// </summary>
        /// <param name="puntuazioaService"></param>
        public HallOfShameViewComponent(IPuntuazioaService puntuazioaService)
        {
            _puntuazioaService = puntuazioaService;
        }
        /// <summary>
        ///  View-ra bidaltzen dio puntuazio txarrenen informazioa
        /// </summary>
        /// <returns>Puntuazio txarrenak itzuli</returns>
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await _puntuazioaService.GetHallOfShame());

        }
    }
}

Visual(Interfaze)/SuperNaaahi/SuperNaaahi/ViewComponents/PuntuazioakViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SuperNaaahi.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SuperNaaahi.ViewComponents
{
    /// <summary>
    /// Puntuazio guztien  view-rako konponenteen viw-a
    /// </summary>
    public class PuntuazioakViewComponent: ViewComponent
    {
        private readonly IPuntuazioaService _puntuazioaService;

        /// <summary>
        /// Puntuazio guzien ViewComponent-earen konstruktorea
        /// </summary>
        /// <param name="puntuazioaService"></param>
        public PuntuazioakViewComponent(IPuntuazioaService puntuazioaService)
        {
            _puntuazioaService = puntuazioaService;
        }
        /// <summary>
        /// View-ra bidaltzen dio puntuazio guztien informazioa
        /// </summary>
        /// <returns>Puntuazio guztiak itzuli </returns>
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await _puntuazioaService.GetPuntuazioak());

        }
    
    }
}

Visual(Interfaze)/SuperNaaahi/SuperNaaahi/Views/Home/Foroa.cshtml
@{
    ViewData["Title"] = "Foroa";
    @model SuperNaaahi.Models.Foroa
}

<h1>@ViewData["Title"]</h1>

<div class="row">
    <div class="col-8">
        <br />
        @await Component.InvokeAsync("Foroa")
        <br />

    </div>
    <div class="col-4">
        <h5 class="display-5">Laga hemen zure komentarioak</h5>
        <br />
        <form asp-action="Foroa">
            <div class="form-group">

                <label asp-for="Korreoa" class="control-label"></label>
                <input asp-for="Korreoa" class="form-control" value="@User.Identity.Name" readonly />
                <span asp-validation-for="Korreoa" class="text-danger"></span>
                <br />
                <label asp-for="Komentarioa">Komentarioa</label>
                <textarea asp-for="Komentarioa" class="form-control komentarioakSartzekoLekua" id="komentarioa"></textarea>
                <span asp-validation-for="Komentarioa"></span>
            </div>

            <button type="submit" class="btn btn-primary">Komentatu</button>

        </form>
    </div>
</div>
<script>
       document.getElementById("komentarioa").value = "";
</script>

Visual(Interfaze)/SuperNaaahi/SuperNaaahi/Views/Home/General.cshtml
@model IEnumerable<SuperNaaahi.Models.PuntuazioaModel>

@{
    ViewData["Title"] = "Ranking orokorra";
}

<h1>@ViewData["Title"]</h1>

<br />

@await Component.InvokeAsync("Puntuazioak")

Visual(Interfaze)/SuperNaaahi/SuperNaaahi/Views/Home/HallOfFame.cshtml
@model IEnumerable<SuperNaaahi.Models.PuntuazioaModel>

@{
    ViewData["Title"] = "Hall Of Fame";
}
<h1>@ViewData["Title"]</h1>

<br />

@await Component.InvokeAsync("HallOfFame")

Visual(Interfaze)/SuperNaaahi/SuperNaaahi/Views/Home/HallOfShame.cshtml
@{
    ViewData["Title"] = "Hall Of Shame";
}
<h1>@ViewData["Title"]</h1>

<br />

@await Component.InvokeAsync("HallOfShame")

Visual(Interfaze)/SuperNaaahi/SuperNaaahi/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">NORTZUK GARA? </h1>
    <img src="~/images/supernaaahi.png" class="argazkiaIndex" />
    <div class="informazioaIndex">
        <p>Gure enpresa SuperNaaahi deitzen da. Eta elikagaien salmentan aritzen gara.</p>
        <p>Web orri honetan aurkituko duzu gure langileen artean antolatutako txapelketa</p>
        <p>Txapelketako informazioa ikusteko logeatu behar zara</p>

    </div>

    @if (Model != null)
    {

        <b><a class="nav-link inkestaLinka" asp-area="" asp-controller="Home" asp-action="Inkesta" onclick="return alert ('Inkesta beteta daukazu iadanik')">Inkesta betetzeko klikatu hemen</a></b>
       
    }
    else
    {
        <b><a class="nav-link inkestaLinka" asp-area="" asp-controller="Home" asp-action="Inkesta" >Inkesta betetzeko klikatu hemen</a></b>
    }



</div>

Visual(Interfaze)/SuperNaaahi/SuperNaaahi/Views/Home/Inkesta.cshtml
@model SuperNaaahi.Models.Inkesta
@{
    ViewData["Title"] = "Inkesta";
}

<h1>Inkesta</h1>
<hr />
<br/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Inkesta">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Korreoa" class="control-label"></label>
                <input asp-for="Korreoa" class="form-control" value="@User.Identity.Name" readonly />
                <span asp-validation-for="Korreoa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Balorazioa" class="control-label"></label>
                <input asp-for="Balorazioa" class="form-control" max="10" min="0" />
                <span asp-validation-for="Balorazioa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hobetzeko" class="control-label"></label>
                <textarea asp-for="Hobetzeko" class="form-control komentarioakSartzekoLekua"></textarea>
                <span asp-validation-for="Hobetzeko" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Gomendatu" /> @Html.DisplayNameFor(model => model.Gomendatu)
                </label>
            </div>
            <!--
       return confirm ('Ziur zaude inkesta bidali nahi duzula?')
    -->
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" onclick="return alert ('Ziur zaude inkesta bidali nahi duzula?');" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Itzuli</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}